[project]
name = "project-3-autograder"
version = "0.1.0"
description = "verifies each submitted module"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradescope-utils>=0.5.0",
]
